WEB.MVC5/Models/Lunch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WEB.MVC5.Models
{
	public class Lunch
	{
		public int LunchId { get; set; }

		[Display(Name = "Дата обеда")]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd'.'MM'.'yyyy}")]
		[DataType(DataType.Date)]
		public DateTime Date { get; set; }

		[Display(Name = "Салат")]
		public int SaladId { get; set; }
		public Salad Salad { get; set; }

		//[Required]
		[Display(Name = "Суп")]
		public int SoupId { get; set; }
		//[ForeignKey("CountryId")]
		public Soup Soup { get; set; }

		[Display(Name = "Гарнир")]
		public int GarnishId { get; set; }
		public Garnish Garnish { get; set; }

		[Display(Name = "Мясное блюдо")]
		public int MeatDishId { get; set; }
		public MeatDish MeatDish { get; set; }

		[Display(Name = "Хлеб")]
		public int BreadId { get; set; }
		public Bread Bread { get; set; }

		[Display(Name = "Список блюд")]
		[DataType(DataType.MultilineText)]
		public string Menu { get; set; }

		[Display(Name = "Стоимость обеда")]
		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal PriceWithSoup { get; set; }

		[Display(Name = "Стоимость без первого")]
		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal PriceWithoutSoup { get; set; }

		public ICollection<Order> Orders { get; set; }

	}
}

WEB.MVC5/Models/LunchViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WEB.MVC5.Models
{
	/*public class OrderViewModels
	{
		[Display(Name = "Дата обеда")]
		public DateTime Date { get; set; }

		[Display(Name = "Список блюд")]
		public string Menu { get; set; }

		[Display(Name = "Стоимость обеда")]
		public decimal PriceWithSoup { get; set; }

		[Display(Name = "Стоимость без первого")]
		public decimal PriceWithoutSoup { get; set; }

		[Display(Name = "Заказать без первого")]
		public bool IsWithoutSoup { get; set; }
	}*/
}

WEB.MVC5/Controllers/BreadsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WEB.MVC5.Models;
using WEB.MVC5.Repository;
using Ninject;

namespace WEB.MVC5.Controllers
{
	[Authorize(Roles = "admin")]
	public class BreadsController : Controller
    {
        //private LunchContext db = new LunchContext();

		private IGenericRepository<Bread> repository = null;

		public BreadsController(IGenericRepository<Bread> repositoryBread)
		{
			//this.repository = new GenericRepository<Bread>();

			/*IKernel ninjectKernel = new StandardKernel();
			ninjectKernel.Bind<IGenericRepository<Bread>>().To<GenericRepository<Bread>>();
			this.repository = ninjectKernel.Get<IGenericRepository<Bread>>();*/

			this.repository = repositoryBread;
		}

		// GET: Breads
		public ActionResult Index()
        {
			var breads = repository.SelectAll().ToList().OrderBy(b => b.Name);
			return View(breads);

			/*var breads = db.Breads.OrderBy(b => b.Name);

			return View(await breads.ToListAsync());*/
		}

        // GET: Breads/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Breads/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BreadId,Name,Weight")] Bread bread)
        {
            if (ModelState.IsValid)
            {
				repository.Insert(bread);
				repository.Save();
				/*db.Breads.Add(bread);
                await db.SaveChangesAsync();*/

				return RedirectToAction("Index");
            }

            return View(bread);
        }

        // GET: Breads/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

			var bread = repository.SelectByID(id);

			//Bread bread = await db.Breads.FindAsync(id);
            if (bread == null)
            {
                return HttpNotFound();
            }
            return View(bread);
        }

        // POST: Breads/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BreadId,Name,Weight")] Bread bread)
        {
            if (ModelState.IsValid)
            {
				repository.Update(bread);
				repository.Save();
				/*db.Entry(bread).State = EntityState.Modified;
                await db.SaveChangesAsync();*/
				return RedirectToAction("Index");
            }
            return View(bread);
        }

        // GET: Breads/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			var bread = repository.SelectByID(id);
			//Bread bread = await db.Breads.FindAsync(id);
            if (bread == null)
            {
                return HttpNotFound();
            }
            return View(bread);
        }

        // POST: Breads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
			repository.Delete(id);
			repository.Save();

			/*Bread bread = await db.Breads.FindAsync(id);
            db.Breads.Remove(bread);
            await db.SaveChangesAsync();*/

            return RedirectToAction("Index");
        }

		/*protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				repository.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

WEB.MVC5/Controllers/LunchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WEB.MVC5.Models;
using WEB.MVC5.Repository;

namespace WEB.MVC5.Controllers
{
	public class LunchesController : Controller
    {
		private ILunchRepository repository = null;

		public LunchesController(ILunchRepository repositoryLunch)
		{
			this.repository = repositoryLunch;
		}

		// GET: Lunches
		[Authorize(Roles = "admin")]
		public ActionResult Index()
        {
			var lunches = repository.SelectAll().ToList().OrderByDescending(l => l.Date);

			return View(lunches);
        }

		// GET: Lunches/Create
		[Authorize(Roles = "admin")]
		public ActionResult Create()
        {
            ViewBag.BreadId = new SelectList(repository.SelectAllBreads(), "BreadId", "Name").OrderBy(b => b.Text);
            ViewBag.GarnishId = new SelectList(repository.SelectAllGarnishes(), "GarnishId", "Name").OrderBy(g => g.Text);
            ViewBag.MeatDishId = new SelectList(repository.SelectAllMeatDishes(), "MeatDishId", "Name").OrderBy(md => md.Text);
            ViewBag.SaladId = new SelectList(repository.SelectAllSalads(), "SaladId", "Name").OrderBy(s => s.Text);
            ViewBag.SoupId = new SelectList(repository.SelectAllSoups(), "SoupId", "Name").OrderBy(s => s.Text);

            return View();
        }

        // POST: Lunches/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "admin")]
		public ActionResult Create([Bind(Include = "LunchId,Date,SaladId,SoupId,GarnishId,MeatDishId,BreadId,Menu,PriceWithSoup,PriceWithoutSoup")] Lunch lunch)
        {
            if (ModelState.IsValid)
            {
				repository.Insert(lunch);
				repository.Save();

                return RedirectToAction("Index");
            }

            ViewBag.BreadId = new SelectList(repository.SelectAllBreads(), "BreadId", "Name", lunch.BreadId);
            ViewBag.GarnishId = new SelectList(repository.SelectAllGarnishes(), "GarnishId", "Name", lunch.GarnishId);
            ViewBag.MeatDishId = new SelectList(repository.SelectAllMeatDishes(), "MeatDishId", "Name", lunch.MeatDishId);
            ViewBag.SaladId = new SelectList(repository.SelectAllSalads(), "SaladId", "Name", lunch.SaladId);
            ViewBag.SoupId = new SelectList(repository.SelectAllSoups(), "SoupId", "Name", lunch.SoupId);

            return View(lunch);
        }

		// GET: Lunches/Edit/5
		[Authorize(Roles = "admin")]
		public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

			var lunch = repository.SelectByID(id);

            if (lunch == null)
            {
                return HttpNotFound();
            }

            ViewBag.BreadId = new SelectList(repository.SelectAllBreads(), "BreadId", "Name", lunch.BreadId).OrderBy(b => b.Text);
            ViewBag.GarnishId = new SelectList(repository.SelectAllGarnishes(), "GarnishId", "Name", lunch.GarnishId).OrderBy(g => g.Text);
            ViewBag.MeatDishId = new SelectList(repository.SelectAllMeatDishes(), "MeatDishId", "Name", lunch.MeatDishId).OrderBy(md => md.Text);
            ViewBag.SaladId = new SelectList(repository.SelectAllSalads(), "SaladId", "Name", lunch.SaladId).OrderBy(s => s.Text);
            ViewBag.SoupId = new SelectList(repository.SelectAllSoups(), "SoupId", "Name", lunch.SoupId).OrderBy(s => s.Text);

            return View(lunch);
        }

        // POST: Lunches/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "admin")]
		public ActionResult Edit([Bind(Include = "LunchId,Date,SaladId,SoupId,GarnishId,MeatDishId,BreadId,Menu,PriceWithSoup,PriceWithoutSoup")] Lunch lunch)
        {
            if (ModelState.IsValid)
            {
				repository.Update(lunch);
				repository.Save();

                return RedirectToAction("Index");
            }

            ViewBag.BreadId = new SelectList(repository.SelectAllBreads(), "BreadId", "Name", lunch.BreadId);
            ViewBag.GarnishId = new SelectList(repository.SelectAllGarnishes(), "GarnishId", "Name", lunch.GarnishId);
            ViewBag.MeatDishId = new SelectList(repository.SelectAllMeatDishes(), "MeatDishId", "Name", lunch.MeatDishId);
            ViewBag.SaladId = new SelectList(repository.SelectAllSalads(), "SaladId", "Name", lunch.SaladId);
            ViewBag.SoupId = new SelectList(repository.SelectAllSoups(), "SoupId", "Name", lunch.SoupId);

            return View(lunch);
        }

		// GET: Lunches/Delete/5
		[Authorize(Roles = "admin")]
		public ActionResult Delete(int? id)
        {
			if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

			var lunch = repository.SelectByID(id);

			if (lunch == null)
            {
                return HttpNotFound();
            }

            return View(lunch);
        }

        // POST: Lunches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		[Authorize(Roles = "admin")]
		public ActionResult DeleteConfirmed(int id)
        {
			repository.Delete(id);
			repository.Save();

            return RedirectToAction("Index");
        }

		// GET: Lunches/ActualLunches
		[Authorize(Roles = "admin, user")]
		public ActionResult ActualLunches()
		{
			var lunches = repository.SelectAll().ToList().OrderBy(l => l.Date).Where(l => l.Date.Date >= DateTime.Now.Date);

			return View(lunches);
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				repository.Dispose();
			}

			base.Dispose(disposing);
		}
	}
}

WEB.MVC5/Controllers/SoupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WEB.MVC5.Models;
using WEB.MVC5.Repository;

namespace WEB.MVC5.Controllers
{
	[Authorize(Roles = "admin")]
	public class SoupsController : Controller
    {
		private IGenericRepository<Soup> repository = null;

		public SoupsController(IGenericRepository<Soup> repositorySoup)
		{
			this.repository = repositorySoup;
		}

		// GET: Soups
		public ActionResult Index()
        {
			var soups = repository.SelectAll().ToList().OrderBy(s => s.Name);

			return View(soups);
        }

        // GET: Soups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Soups/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SoupId,Name,Weight")] Soup soup)
        {
            if (ModelState.IsValid)
            {
				repository.Insert(soup);
				repository.Save();

                return RedirectToAction("Index");
            }

            return View(soup);
        }

        // GET: Soups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

			var soup = repository.SelectByID(id);

            if (soup == null)
            {
                return HttpNotFound();
            }

            return View(soup);
        }

        // POST: Soups/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SoupId,Name,Weight")] Soup soup)
        {
            if (ModelState.IsValid)
            {
				repository.Update(soup);
				repository.Save();

                return RedirectToAction("Index");
            }

            return View(soup);
        }

        // GET: Soups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

			var soup = repository.SelectByID(id);

            if (soup == null)
            {
                return HttpNotFound();
            }

            return View(soup);
        }

        // POST: Soups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
			repository.Delete(id);
			repository.Save();

            return RedirectToAction("Index");
        }

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				repository.Dispose();
			}

			base.Dispose(disposing);
		}
	}
}

WEB.MVC5/Views/Lunches/ActualLunches.cshtml
@model IEnumerable<WEB.MVC5.Models.Lunch>

@{
	ViewBag.Title = "Актуальное меню";
}

<h2>Актуальное меню</h2>
<h4>@Html.ActionLink("Оформить заказ", "Order", "Orders")</h4>

@foreach (var item in Model)
{
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">@Html.DisplayNameFor(model => model.Date): @Html.DisplayFor(modelItem => item.Date) - @DateTimeFormatInfo.CurrentInfo.GetDayName(item.Date.DayOfWeek)</h3>
		</div>
		<div class="panel-body">
			<label>Меню:</label><br />
			@Html.DisplayFor(modelItem => item.Salad.Name) (@Html.DisplayFor(modelItem => item.Salad.Description))
			@for (int i = 0; i < item.Salad.Rating; i++)
			{
				<img class="" width="20" height="20" src="~/Content/img/star.png" />
			}
			<br />
			@Html.DisplayFor(modelItem => item.Soup.Name)
			@for (int i = 0; i < item.Soup.Rating; i++)
			{
				<img class="" width="20" height="20" src="~/Content/img/star.png" />
			}
			<br />
			@Html.DisplayFor(modelItem => item.MeatDish.Name)
			@for (int i = 0; i < item.MeatDish.Rating; i++)
			{
				<img class="" width="20" height="20" src="~/Content/img/star.png" />
			}
			<br />
			@Html.DisplayFor(modelItem => item.Garnish.Name)
			@for (int i = 0; i < item.Garnish.Rating; i++)
			{
				<img class="" width="20" height="20" src="~/Content/img/star.png" />
			}
			<br />
			@Html.DisplayFor(modelItem => item.Bread.Name)
			<hr />
			<label>Стоимость:</label><br />
			@Html.DisplayNameFor(model => model.PriceWithSoup) - @Html.DisplayFor(modelItem => item.PriceWithSoup)
			<br />
			@Html.DisplayNameFor(model => model.PriceWithoutSoup) - @Html.DisplayFor(modelItem => item.PriceWithoutSoup)
		</div>
		<div class="panel-footer">
			<label>Общий рейтинг: </label>
			@for (int i = 0; i < (item.Salad.Rating + item.Garnish.Rating + item.Soup.Rating + item.MeatDish.Rating) / 4; i++)
			{
				<img class="" width="20" height="20" src="~/Content/img/star.png" />
			}
		</div>
	</div>
}

WEB.MVC5/Views/Lunches/Create.cshtml
@model WEB.MVC5.Models.Lunch

@{
    ViewBag.Title = "Создать обед";
}

<h2>Создать</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Обед</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SaladId, "Салат", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SaladId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SaladId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoupId, "Суп", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SoupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoupId, "", new { @class = "text-danger" })
            </div>
        </div>
	  
        <div class="form-group">
            @Html.LabelFor(model => model.MeatDishId, "Мясное блюдо", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MeatDishId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MeatDishId, "", new { @class = "text-danger" })
            </div>
        </div>

		<div class="form-group">
			@Html.LabelFor(model => model.GarnishId, "Гарнир", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("GarnishId", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.GarnishId, "", new { @class = "text-danger" })
			</div>
		</div>

        <div class="form-group">
            @Html.LabelFor(model => model.BreadId, "Хлеб", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BreadId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BreadId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceWithSoup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceWithSoup, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceWithSoup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceWithoutSoup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceWithoutSoup, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceWithoutSoup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Записать" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<a href="/Lunches" title="Вернуться назад"><img class="img-circle" width="50" height="50" src="~/Content/img/back_blue.png" /></a>

WEB.MVC5/Views/Lunches/Delete.cshtml
@model WEB.MVC5.Models.Lunch

@{
    ViewBag.Title = "Удаление обеда";
}

<h2>Удалить</h2>

<h3>Вы действительно хотите удалить эту запись?</h3>
<div>
	<h4>Обед @Html.DisplayFor(model => model.Date) (@DateTimeFormatInfo.CurrentInfo.GetDayName(Model.Date.DayOfWeek))</h4>
	<hr />
	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Удалить" class="btn btn-primary" /> |
			@Html.ActionLink("Назад", "Index")
		</div>
	}
</div>

WEB.MVC5/Views/Lunches/Edit.cshtml
@model WEB.MVC5.Models.Lunch

@{
    ViewBag.Title = "Редактирование обеда";
}

<h2>Редактировать запись</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Обед</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LunchId)

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SaladId, "Салат", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SaladId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SaladId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoupId, "Суп", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SoupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoupId, "", new { @class = "text-danger" })
            </div>
        </div>

		<div class="form-group">
			@Html.LabelFor(model => model.MeatDishId, "Мясное блюдо", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("MeatDishId", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.MeatDishId, "", new { @class = "text-danger" })
			</div>
		</div>

        <div class="form-group">
            @Html.LabelFor(model => model.GarnishId, "Гарнир", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GarnishId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GarnishId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BreadId, "Хлеб", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BreadId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BreadId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceWithSoup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceWithSoup, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceWithSoup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceWithoutSoup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceWithoutSoup, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceWithoutSoup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<a href="/Lunches" title="Вернуться назад"><img class="img-circle" width="50" height="50" src="~/Content/img/back_blue.png" /></a>

WEB.MVC5/Views/Lunches/Index.cshtml
@model IEnumerable<WEB.MVC5.Models.Lunch>

@{
    ViewBag.Title = "Список обедов";
}
<ul class="nav nav-pills">
	<li>@Html.ActionLink("Салаты", "Index", "Salads")</li>
	<li>@Html.ActionLink("Супы", "Index", "Soups")</li>
	<li>@Html.ActionLink("Мясные блюда", "Index", "MeatDishes")</li>
	<li>@Html.ActionLink("Гарниры", "Index", "Garnishes")</li>
	<li>@Html.ActionLink("Хлеб", "Index", "Breads")</li>
</ul>
<hr />
<h2>Список обедов</h2>
	<p>@Html.ActionLink("Создать обед", "Create")</p>
	<table class="table table-hover">
		<tr class="info">
			<th>
				@Html.DisplayNameFor(model => model.Date)
			</th>
			<th>
				Меню
			</th>
			<th>
				@Html.DisplayNameFor(model => model.PriceWithSoup)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.PriceWithoutSoup)
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Date)
					<br />
					@DateTimeFormatInfo.CurrentInfo.GetDayName(item.Date.DayOfWeek)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Salad.Name)
					<br />
					@Html.DisplayFor(modelItem => item.Soup.Name)
					<br />
					@Html.DisplayFor(modelItem => item.MeatDish.Name)
					<br />
					@Html.DisplayFor(modelItem => item.Garnish.Name)
					<br />
					@Html.DisplayFor(modelItem => item.Bread.Name)
					<br />
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.PriceWithSoup)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.PriceWithoutSoup)
				</td>
				<td>
					@Html.ActionLink("Редактировать", "Edit", new { id = item.LunchId })<br />
					@Html.ActionLink("Удалить", "Delete", new { id = item.LunchId })
				</td>
			</tr>
		}

	</table>