WEB.MVC5/Models/Balance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WEB.MVC5.Models
{
	public class Balance
	{
		public int BalanceId { get; set; }

		public int UserId { get; set; }
		public User User { get; set; }

		[Display(Name = "Дата операции")]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd'.'MM'.'yyyy}")]
		[DataType(DataType.Date)]
		public DateTime Date { get; set; }

		[Display(Name = "Поступление на счет")]
		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal Income { get; set; }

		[Display(Name = "Списание со счета")]
		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal Expence { get; set; }

		[Display(Name = "Назначение операции")]
		public string Comment { get; set; }
	}
}

WEB.MVC5/Models/BalanceViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WEB.MVC5.Models
{
	public class UserBalance
	{
		public int UserId { get; set; }

		public string Name { get; set; }

		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal TotalBalance { get; set; }

		public DateTime Date { get; set; }

		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal Income { get; set; }

		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal Expence { get; set; }

		public string Comment { get; set; }
	}

	public class UserTotalBalance
	{
		public int UserId { get; set; }

		public string Name { get; set; }

		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal UserBalance { get; set; }

		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal TotalBalance { get; set; }
	}
}

WEB.MVC5/Controllers/BalancesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WEB.MVC5.Models;

namespace WEB.MVC5.Controllers
{
    public class BalancesController : Controller
    {
		private LunchContext db = new LunchContext();

		// GET: Balances/MyBalance
		[Authorize(Roles = "user")]
		public ActionResult MyBalance()
		{
			var user = db.Users.Where(u => u.Email == HttpContext.User.Identity.Name).ToList().ElementAt(0);

			var balances = db.Balances.Where(b => b.UserId == user.UserId).OrderByDescending(b => b.Date);

			ViewBag.User = user;

			decimal debit = balances.Any() ? balances.Sum(b => b.Income) : Decimal.Parse("0");
			decimal credit = balances.Any() ? balances.Sum(b => b.Expence) : Decimal.Parse("0");
			ViewBag.Result = debit - credit;

			return View(balances.ToList());
		}

		// GET: Balances/UserBalanceHistory/1
		[Authorize(Roles = "admin")]
		public ActionResult UserBalanceHistory(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var balances = db.Balances.Where(b => b.UserId == id).OrderByDescending(b => b.Date);
			var user = db.Users.Where(u => u.UserId == id).ToList().ElementAt(0);

			ViewBag.User = user;

			decimal debit = balances.Any() ? balances.Sum(b => b.Income) : Decimal.Parse("0");
			decimal credit = balances.Any() ? balances.Sum(b => b.Expence) : Decimal.Parse("0");
			ViewBag.Result = debit - credit;

			return View(balances.ToList());
		}

		/*public ActionResult UsersBalance()
		{
			var users = db.Users;

			var balances = db.Balances;

			var usersBalance = users.Join(
				balances,
				u => u.UserId,
				b => b.UserId,
				(u, b) => new UserBalance {
					UserId = u.UserId,
					Name = u.LastName + " " + u.Name + " - " + u.Email,
					TotalBalance = u.Balance,
					Date = b.Date,
					Income = b.Income,
					Expence = b.Expence,
					Comment = b.Comment }
				).GroupBy(ub => ub.Name);

			return View(usersBalance.ToList());
		}*/

		// GET: Balances/UsersTotalBalance
		[Authorize(Roles = "admin")]
		public ActionResult UsersTotalBalance()
		{
			var users = db.Users;

			var balances = db.Balances;

			var usersTotalBalance = users.GroupJoin(
				balances,
				u => u.UserId,
				b => b.UserId,
				(u, bs) => new UserTotalBalance
				{
					UserId = u.UserId,
					Name = u.LastName + " " + u.Name + " - " + u.Email,
					UserBalance = u.Balance,
					TotalBalance = bs.Sum(b => b.Income ) - bs.Sum(b => b.Expence),
				});

			decimal sum = 0;

			foreach (var item in usersTotalBalance)
				{
					sum += item.TotalBalance;
				}

			ViewBag.Cashbox = sum.ToString("0,0.00", CultureInfo.InvariantCulture);

			return View(usersTotalBalance.ToList().AsEnumerable());
		}

		// GET: Balances/UsersList
		[Authorize(Roles = "user")]
		public ActionResult UsersList()
		{
			return View(db.Users.ToList());
		}

		// GET: Balances/GiveBalance/5
		[Authorize(Roles = "user")]
		public ActionResult GiveBalance(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			User user = db.Users.Find(id);

			if (user == null)
			{
				return HttpNotFound();
			}

			AddBalanceToUser giveBalance = new AddBalanceToUser();
			giveBalance.UserId = user.UserId;
			giveBalance.Name = user.Name;
			giveBalance.LastName = user.LastName;
			giveBalance.Email = user.Email;
			giveBalance.AddBalance = 0;

			var currentUser = db.Users.Where(u => u.Email == HttpContext.User.Identity.Name).ToList().ElementAt(0);

			ViewBag.CurrentUser = currentUser;

			return View(giveBalance);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "user")]
		public async Task<ActionResult> GiveBalance(AddBalanceToUser addBalanceToUser)
		{
			var currentUser = db.Users.Where(u => u.Email == HttpContext.User.Identity.Name).ToList().ElementAt(0);

			if (ModelState.IsValid && addBalanceToUser.AddBalance <= currentUser.Balance && addBalanceToUser.AddBalance > 0)
			{
				User user = await db.Users.FindAsync(addBalanceToUser.UserId);

				if (user == null)
				{
					return HttpNotFound();
				}

				Balance balance = new Balance();
				Balance currentBalance = new Balance();

				user.Balance += addBalanceToUser.AddBalance;
				currentUser.Balance -= addBalanceToUser.AddBalance;

				balance.Date = DateTime.Now;
				balance.UserId = user.UserId;
				balance.Income = addBalanceToUser.AddBalance;
				balance.Comment = "С вами поделился балансом " + currentUser.Name + " " + currentUser.LastName + " (" + currentUser.Email + ")";
				db.Balances.Add(balance);

				currentBalance.Date = DateTime.Now;
				currentBalance.UserId = currentUser.UserId;
				currentBalance.Expence = addBalanceToUser.AddBalance;
				currentBalance.Comment = "Вы поделились балансом с " + user.Name + " " + user.LastName + " (" + user.Email + ")";
				db.Balances.Add(currentBalance);

				db.Entry(user).State = EntityState.Modified;

				await db.SaveChangesAsync();

				return RedirectToAction("UsersList");
			}

			return RedirectToAction("GiveBalance", new { id = addBalanceToUser.UserId });
		}

	}
}

WEB.MVC5/Views/Balances/GiveBalance.cshtml
@model WEB.MVC5.Models.AddBalanceToUser
@{
	ViewBag.Title = "Поделиться балансом";
}

<h2>Поделиться балансом</h2>

<div class="row">
	<div class="col-md-4">
		<div class="panel panel-primary">
			<div class="panel-heading text-center">
				<h3 class="panel-title">@ViewBag.CurrentUser.Name @ViewBag.CurrentUser.LastName</h3>
			</div>
			<div class="panel-body text-center">
				@if (@ViewBag.CurrentUser.PhotoData != null)
				{
					<div class="" style="margin-right: 0px">
						<img class="img-thumbnail" width="100" height="100" src="@Url.Action("GetPhoto", "Profile", new { @ViewBag.CurrentUser.UserId })" />
					</div>
				}
			</div>
			<div class="panel-footer text-center">
				<label> Баланс счета: @ViewBag.CurrentUser.Balance.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</label>
			</div>
		</div>
	</div>
	<div class="col-md-4 text-center">
		<div class="" style="margin-right: 0px">
			<img class="img-thumbnail" width="250" height="250" src="~/Content/img/CoinTransfer.jpg" />
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-primary">

			<div class="panel-heading text-center">
				<h3 class="panel-title">@Model.Name @Model.LastName</h3>
			</div>
			<div class="panel-body text-center">
				<div class="" style="margin-right: 0px">
					<img class="img-thumbnail" width="100" height="100" src="@Url.Action("GetPhoto", "Profile", new { @Model.UserId })" />
				</div>
			</div>
			<div class="panel-footer text-center">
				<label> </label>
			</div>
		</div>

	</div>
</div>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.UserId)

		<div class="form-group">
			@Html.LabelFor(model => model.AddBalance, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.AddBalance, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.AddBalance, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Перевести" class="btn btn-primary" />
			</div>
		</div>
	</div>
}

<a href="/Balances/UsersList" title="Вернуться назад"><img class="img-circle" width="50" height="50" src="~/Content/img/back_blue.png" /></a>

WEB.MVC5/Views/Balances/MyBalance.cshtml
@model IEnumerable<WEB.MVC5.Models.Balance>

@{
	ViewBag.Title = "Журнал учета баланса пользователя";
}

<h3>Журнал учета баланса пользователя:</h3>
<row>
	@if (ViewBag.User.Balance == ViewBag.Result)
	{
		<div class="col-md-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">@ViewBag.User.LastName @ViewBag.User.Name - @ViewBag.User.Email</h3>
				</div>
				<div class="panel-body">
					<h4>Баланс счета составляет: @ViewBag.User.Balance.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</h4>
					<div class="text-right">
						@Html.ActionLink("Поделиться балансом", "UsersList", "Balances")
					</div>
				</div>
			</div>
		</div>
	}
	else
	{
		<div class="col-md-2">
			<div class="text-center" style="margin-right: 0px">
				<img class="img-circle" width="100" height="100" src="~/Content/img/No.png" />
			</div>
			<div class="text-danger text-center">
				<p>Обратитесь к @Html.ActionLink("администратору", "Contact", "Home").</p>
			</div>
		</div>

		<div class="col-md-10">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title">@ViewBag.User.LastName @ViewBag.User.Name - @ViewBag.User.Email</h3>
				</div>
				<div class="panel-body">
					<h4>Баланс счета по журналу кассы составляет: @ViewBag.Result.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</h4>
					<h4>Баланс счета по карточке пользователя составляет: @ViewBag.User.Balance.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</h4>
					<div class="text-right">
						@Html.ActionLink("Поделиться балансом", "UsersList", "Balances")
					</div>
				</div>
			</div>
		</div>
	}	
</row>

<table class="table table-hover">
	<tr class="info">
		<th>
			@Html.DisplayNameFor(model => model.Date)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Income)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Expence)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Comment)
		</th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Date)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Income)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Expence)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Comment)
			</td>
		</tr>
	}

</table>

WEB.MVC5/Views/Balances/UserBalanceHistory.cshtml
@model IEnumerable<WEB.MVC5.Models.Balance>

@{
	ViewBag.Title = "История баланса пользователя";
}
<br />
<row>
	@if (ViewBag.User.Balance == ViewBag.Result)
	{
		<div class="col-md-1">
			<a href="/Balances/UsersTotalBalance" title="Вернуться назад"><img class="img-circle" width="50" height="50" src="~/Content/img/back_blue.png" /></a>
		</div>
		<div class="col-md-11">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">@ViewBag.User.LastName @ViewBag.User.Name - @ViewBag.User.Email</h3>
				</div>
				<div class="panel-body">
					<h4>Баланс счета составляет: @ViewBag.User.Balance.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</h4>
				</div>
			</div>
		</div>
	}
	else
	{
		<div class="col-md-1">
			<a href="/Balances/UsersTotalBalance" title="Вернуться назад"><img class="img-circle" width="50" height="50" src="~/Content/img/back_blue.png" /></a>
		</div>
		<div class="col-md-11">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title">@ViewBag.User.LastName @ViewBag.User.Name - @ViewBag.User.Email</h3>
				</div>
				<div class="panel-body">
					<h4>Баланс счета по журналу кассы составляет: @ViewBag.Result.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</h4>
					<h4>Баланс счета по карточке пользователя составляет: @ViewBag.User.Balance.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</h4>
				</div>
			</div>
		</div>
	}
</row>

<table class="table table-hover">
	<tr class="info">
		<th>
			@Html.DisplayNameFor(model => model.Date)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Income)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Expence)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Comment)
		</th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Date)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Income)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Expence)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Comment)
			</td>
		</tr>
	}
</table>

WEB.MVC5/Views/Balances/UsersBalance.cshtml
@model IEnumerable<IGrouping<string, WEB.MVC5.Models.UserBalance>>

@{
    ViewBag.Title = "UsersBalance";
}

@Html.ActionLink("Назад", "UsersTotalBalance", "Balances")

<h3>Журнал учета движения денежных средств пользователей</h3>

@foreach (var item in Model)
{
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">@item.Key</h3>
		</div>
		<div class="panel-body">
			<table class="table">
				<tr>
					<th>
						Дата операции
					</th>
					<th>
						Поступление на счет
					</th>
					<th>
						Списание со счета
					</th>
					<th>
						Назначение
					</th>
				</tr>
				@foreach (var balance in item)
				{
					<tr>
						<td>
							@balance.Date
						</td>
						<td>
							@balance.Income
						</td>
						<td>
							@balance.Expence
						</td>
						<td>
							@balance.Comment
						</td>
					</tr>
				}
			</table>
		</div>
	</div>
}

WEB.MVC5/Views/Balances/UsersList.cshtml
@model IEnumerable<WEB.MVC5.Models.User>

@{
	ViewBag.Title = "Список пользователей";
}

<h2>Список пользователей</h2>
<br />
<table class="table table-hover">
	<tr class="info">
		<th>
			Фото
		</th>
		<th>
			Данные пользователя
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		if (item.Email != Context.User.Identity.Name)
		{
			<tr>
				<td>
					@if (item.PhotoData != null)
					{
						<div class="pull-left" style="margin-right: 10px">
							<img class="img-thumbnail" width="100" height="100" src="@Url.Action("GetPhoto", "Profile", new { item.UserId })" />
						</div>
					}
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.LastName)
					@Html.DisplayFor(modelItem => item.Name)
					<br />
					@Html.DisplayFor(modelItem => item.Phone)
					<br />
					@Html.DisplayFor(modelItem => item.Email)
				</td>

				<td>
					@Html.ActionLink("Поделиться балансом", "GiveBalance", new { id = @item.UserId })
				</td>
			</tr>
		}
	}

</table>
<a href="/Balances/MyBalance" title="Вернуться назад"><img class="img-circle" width="50" height="50" src="~/Content/img/back_blue.png" /></a>

WEB.MVC5/Views/Balances/UsersTotalBalance.cshtml
@model IEnumerable<WEB.MVC5.Models.UserTotalBalance>

@{
	ViewBag.Title = "Касса";
}
@*Html.ActionLink("Журнал учета движения денежных средств пользователей", "UsersBalance", "Balances")*@

<h3>Остаток денежных средств в кассе: <b>@ViewBag.Cashbox руб.</b></h3>
<br />

@foreach (var item in Model)
{
	if (@item.TotalBalance == @item.UserBalance)
	{
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h2 class="panel-title">@item.Name</h2>
			</div>
			<div class="panel-body">
				<h4>Баланс счета составляет: @item.TotalBalance.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</h4>
			</div>
			<div class="panel-footer">
				<label> @Html.ActionLink("Просмотреть историю баланса", "UserBalanceHistory", new { id = @item.UserId })</label>
			</div>
		</div>
	}
	else
	{
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">@item.Name</h2>
			</div>
			<div class="panel-body">
				<h4>Баланс счета по журналу кассы составляет: @item.TotalBalance.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</h4>
				<h4>Баланс счета по карточке пользователя составляет: @item.UserBalance.ToString("0,0.00", CultureInfo.InvariantCulture) руб.</h4>
			</div>
			<div class="panel-footer">
				<label> @Html.ActionLink("Просмотреть историю баланса", "UserBalanceHistory", new { id = @item.UserId })</label>
			</div>
		</div>
	}
}